import type { University, Program } from "./types";

const VERIFIED = "2026-06-04";

export const SEED_UNIVERSITIES: University[] = [
  { id: "melbourne",       country: "AU", name: "University of Melbourne",     city: "Melbourne", rankingTier: 1, source: "https://study.unimelb.edu.au/how-to-apply/undergraduate-study/international-applications/entry-requirements", lastVerified: VERIFIED, dataQuality: "primary" },
  { id: "unsw",            country: "AU", name: "UNSW Sydney",                 city: "Sydney",    rankingTier: 1, source: "https://www.unsw.edu.au/study/how-to-apply/international/entry-requirements", lastVerified: VERIFIED, dataQuality: "primary" },
  { id: "sydney",          country: "AU", name: "University of Sydney",        city: "Sydney",    rankingTier: 1, source: "https://www.sydney.edu.au/study/fees-and-loans/international-student-tuition-fees.html", lastVerified: VERIFIED, dataQuality: "primary" },
  { id: "monash",          country: "AU", name: "Monash University",           city: "Melbourne", rankingTier: 1, source: "https://www.monash.edu/admissions/entry-requirements/minimum", lastVerified: VERIFIED, dataQuality: "primary" },
  { id: "anu",             country: "AU", name: "Australian National University", city: "Canberra", rankingTier: 1, source: "https://study.anu.edu.au/apply/international-applications", lastVerified: VERIFIED, dataQuality: "primary" },
  { id: "uq",              country: "AU", name: "University of Queensland",    city: "Brisbane",  rankingTier: 1, source: "https://study.uq.edu.au/admissions/english-language-requirements", lastVerified: VERIFIED, dataQuality: "primary" },
  { id: "uwa",             country: "AU", name: "University of Western Australia", city: "Perth", rankingTier: 1, source: "https://www.uwa.edu.au/study/how-to-apply/entry-requirements", lastVerified: VERIFIED, dataQuality: "primary" },
  { id: "adelaide",        country: "AU", name: "University of Adelaide",      city: "Adelaide",  rankingTier: 1, source: "https://www.adelaide.edu.au/study/international/", lastVerified: VERIFIED, dataQuality: "secondary" },
  { id: "uts",             country: "AU", name: "University of Technology Sydney", city: "Sydney", rankingTier: 2, source: "https://www.uts.edu.au/for-students/admissions-entry/how-to-apply/international-applicants/academic-entry-requirements", lastVerified: VERIFIED, dataQuality: "primary" },
  { id: "rmit",            country: "AU", name: "RMIT University",             city: "Melbourne", rankingTier: 2, source: "https://www.rmit.edu.au/study-with-us/international-students/apply-to-rmit-international-students/entry-requirements/country-equivalency/nepal", lastVerified: VERIFIED, dataQuality: "primary" },
  { id: "macquarie",       country: "AU", name: "Macquarie University",        city: "Sydney",    rankingTier: 2, source: "https://www.mq.edu.au/study/international-students/admissions", lastVerified: VERIFIED, dataQuality: "secondary" },
  { id: "deakin",          country: "AU", name: "Deakin University",           city: "Melbourne", rankingTier: 2, source: "https://www.deakin.edu.au/international-students/entry-requirements", lastVerified: VERIFIED, dataQuality: "primary" },
  { id: "curtin",          country: "AU", name: "Curtin University",           city: "Perth",     rankingTier: 2, source: "https://www.curtin.edu.au/study/international/", lastVerified: VERIFIED, dataQuality: "secondary" },
  { id: "latrobe",         country: "AU", name: "La Trobe University",         city: "Melbourne", rankingTier: 2, source: "https://www.latrobe.edu.au/international", lastVerified: VERIFIED, dataQuality: "secondary" },
  { id: "wsu",             country: "AU", name: "Western Sydney University",   city: "Sydney",    rankingTier: 2, source: "https://www.westernsydney.edu.au/international/studying/entry-requirements", lastVerified: VERIFIED, dataQuality: "primary" },
];

export const SEED_PROGRAMS: Program[] = [
  // Melbourne
  { id: "melbourne-bcom", universityId: "melbourne", name: "Bachelor of Commerce", level: "bachelors", field: "business", tuitionMin: 50000, tuitionMax: 55000, tuitionCurrency: "AUD", minGrade: 80, minEnglish: 6.5, minEnglishBand: 6.0, intakes: ["feb","jul"], source: "https://study.unimelb.edu.au", lastVerified: VERIFIED, dataQuality: "derived", notes: null },
  { id: "melbourne-mit",  universityId: "melbourne", name: "Master of Information Technology", level: "masters", field: "computer-science", tuitionMin: 50000, tuitionMax: 55000, tuitionCurrency: "AUD", minGrade: 65, minEnglish: 6.5, minEnglishBand: 6.0, intakes: ["feb","jul"], source: "https://study.unimelb.edu.au", lastVerified: VERIFIED, dataQuality: "derived", notes: null },
  { id: "melbourne-meng", universityId: "melbourne", name: "Master of Engineering", level: "masters", field: "engineering", tuitionMin: 51000, tuitionMax: 56000, tuitionCurrency: "AUD", minGrade: 65, minEnglish: 6.5, minEnglishBand: 6.0, intakes: ["feb","jul"], source: "https://study.unimelb.edu.au", lastVerified: VERIFIED, dataQuality: "derived", notes: null },
  { id: "melbourne-mds",  universityId: "melbourne", name: "Master of Data Science", level: "masters", field: "data-science", tuitionMin: 50000, tuitionMax: 55000, tuitionCurrency: "AUD", minGrade: 70, minEnglish: 6.5, minEnglishBand: 6.0, intakes: ["feb","jul"], source: "https://study.unimelb.edu.au", lastVerified: VERIFIED, dataQuality: "derived", notes: null },

  // UNSW
  { id: "unsw-beng",   universityId: "unsw", name: "Bachelor of Engineering (Hons)", level: "bachelors", field: "engineering", tuitionMin: 55000, tuitionMax: 60000, tuitionCurrency: "AUD", minGrade: 85, minEnglish: 6.5, minEnglishBand: 6.0, intakes: ["feb","jul"], source: "https://www.unsw.edu.au", lastVerified: VERIFIED, dataQuality: "derived", notes: null },
  { id: "unsw-mit",    universityId: "unsw", name: "Master of Information Technology", level: "masters", field: "computer-science", tuitionMin: 52000, tuitionMax: 58000, tuitionCurrency: "AUD", minGrade: 65, minEnglish: 6.5, minEnglishBand: 6.0, intakes: ["feb","jul"], source: "https://www.unsw.edu.au", lastVerified: VERIFIED, dataQuality: "derived", notes: null },
  { id: "unsw-mcom",   universityId: "unsw", name: "Master of Commerce", level: "masters", field: "business", tuitionMin: 53000, tuitionMax: 58000, tuitionCurrency: "AUD", minGrade: 65, minEnglish: 7.0, minEnglishBand: 6.0, intakes: ["feb","jul"], source: "https://www.unsw.edu.au", lastVerified: VERIFIED, dataQuality: "derived", notes: null },
  { id: "unsw-mds",    universityId: "unsw", name: "Master of Data Science & Decisions", level: "masters", field: "data-science", tuitionMin: 53000, tuitionMax: 58000, tuitionCurrency: "AUD", minGrade: 70, minEnglish: 6.5, minEnglishBand: 6.0, intakes: ["feb","jul"], source: "https://www.unsw.edu.au", lastVerified: VERIFIED, dataQuality: "derived", notes: null },

  // Sydney
  { id: "sydney-bcom",  universityId: "sydney", name: "Bachelor of Commerce", level: "bachelors", field: "business", tuitionMin: 53000, tuitionMax: 58000, tuitionCurrency: "AUD", minGrade: 80, minEnglish: 7.0, minEnglishBand: 6.0, intakes: ["feb","jul"], source: "https://www.sydney.edu.au", lastVerified: VERIFIED, dataQuality: "derived", notes: null },
  { id: "sydney-mit",   universityId: "sydney", name: "Master of Information Technology", level: "masters", field: "computer-science", tuitionMin: 52000, tuitionMax: 57000, tuitionCurrency: "AUD", minGrade: 65, minEnglish: 6.5, minEnglishBand: 6.0, intakes: ["feb","jul"], source: "https://www.sydney.edu.au", lastVerified: VERIFIED, dataQuality: "derived", notes: null },
  { id: "sydney-mpe",   universityId: "sydney", name: "Master of Professional Engineering", level: "masters", field: "engineering", tuitionMin: 53000, tuitionMax: 58000, tuitionCurrency: "AUD", minGrade: 65, minEnglish: 6.5, minEnglishBand: 6.0, intakes: ["feb","jul"], source: "https://www.sydney.edu.au", lastVerified: VERIFIED, dataQuality: "derived", notes: null },
  { id: "sydney-mnurs", universityId: "sydney", name: "Master of Nursing", level: "masters", field: "nursing", tuitionMin: 49000, tuitionMax: 53000, tuitionCurrency: "AUD", minGrade: 70, minEnglish: 7.0, minEnglishBand: 7.0, intakes: ["feb","jul"], source: "https://www.sydney.edu.au", lastVerified: VERIFIED, dataQuality: "derived", notes: "AHPRA registration required" },

  // Monash
  { id: "monash-bbus",  universityId: "monash", name: "Bachelor of Business", level: "bachelors", field: "business", tuitionMin: 47000, tuitionMax: 52000, tuitionCurrency: "AUD", minGrade: 75, minEnglish: 6.5, minEnglishBand: 6.0, intakes: ["feb","jul"], source: "https://www.monash.edu", lastVerified: VERIFIED, dataQuality: "derived", notes: null },
  { id: "monash-mit",   universityId: "monash", name: "Master of Information Technology", level: "masters", field: "computer-science", tuitionMin: 46000, tuitionMax: 52000, tuitionCurrency: "AUD", minGrade: 60, minEnglish: 6.5, minEnglishBand: 6.0, intakes: ["feb","jul"], source: "https://www.monash.edu", lastVerified: VERIFIED, dataQuality: "derived", notes: null },
  { id: "monash-mds",   universityId: "monash", name: "Master of Data Science", level: "masters", field: "data-science", tuitionMin: 47000, tuitionMax: 53000, tuitionCurrency: "AUD", minGrade: 65, minEnglish: 6.5, minEnglishBand: 6.0, intakes: ["feb","jul"], source: "https://www.monash.edu", lastVerified: VERIFIED, dataQuality: "derived", notes: null },
  { id: "monash-mnurs", universityId: "monash", name: "Master of Nursing Practice", level: "masters", field: "nursing", tuitionMin: 47000, tuitionMax: 51000, tuitionCurrency: "AUD", minGrade: 65, minEnglish: 7.0, minEnglishBand: 7.0, intakes: ["feb"], source: "https://www.monash.edu", lastVerified: VERIFIED, dataQuality: "derived", notes: "AHPRA registration required" },
  { id: "monash-mba-ai",universityId: "monash", name: "Master of Business Analytics / AI", level: "masters", field: "data-science", tuitionMin: 50000, tuitionMax: 55000, tuitionCurrency: "AUD", minGrade: 65, minEnglish: 6.5, minEnglishBand: 6.0, intakes: ["feb","jul"], source: "https://www.monash.edu", lastVerified: VERIFIED, dataQuality: "derived", notes: null },

  // ANU
  { id: "anu-bit",      universityId: "anu", name: "Bachelor of Information Technology", level: "bachelors", field: "computer-science", tuitionMin: 48000, tuitionMax: 52000, tuitionCurrency: "AUD", minGrade: 80, minEnglish: 6.5, minEnglishBand: 6.0, intakes: ["feb","jul"], source: "https://study.anu.edu.au", lastVerified: VERIFIED, dataQuality: "primary", notes: null },
  { id: "anu-mcomp",    universityId: "anu", name: "Master of Computing", level: "masters", field: "computer-science", tuitionMin: 53700, tuitionMax: 53700, tuitionCurrency: "AUD", minGrade: 65, minEnglish: 6.5, minEnglishBand: 6.0, intakes: ["feb","jul"], source: "https://programsandcourses.anu.edu.au/program/7706XMCOMP", lastVerified: VERIFIED, dataQuality: "primary", notes: null },
  { id: "anu-meng",     universityId: "anu", name: "Master of Engineering", level: "masters", field: "engineering", tuitionMin: 50000, tuitionMax: 55000, tuitionCurrency: "AUD", minGrade: 65, minEnglish: 6.5, minEnglishBand: 6.0, intakes: ["feb","jul"], source: "https://study.anu.edu.au", lastVerified: VERIFIED, dataQuality: "derived", notes: null },
  { id: "anu-mba",      universityId: "anu", name: "Master of Business Administration", level: "masters", field: "business", tuitionMin: 60000, tuitionMax: 65000, tuitionCurrency: "AUD", minGrade: 65, minEnglish: 6.5, minEnglishBand: 6.0, intakes: ["feb","jul"], source: "https://study.anu.edu.au", lastVerified: VERIFIED, dataQuality: "derived", notes: "Work experience required" },

  // UQ
  { id: "uq-beng",      universityId: "uq", name: "Bachelor of Engineering (Hons)", level: "bachelors", field: "engineering", tuitionMin: 50000, tuitionMax: 55000, tuitionCurrency: "AUD", minGrade: 80, minEnglish: 6.5, minEnglishBand: 6.0, intakes: ["feb","jul"], source: "https://study.uq.edu.au", lastVerified: VERIFIED, dataQuality: "derived", notes: null },
  { id: "uq-mcs",       universityId: "uq", name: "Master of Computer Science", level: "masters", field: "computer-science", tuitionMin: 49000, tuitionMax: 54000, tuitionCurrency: "AUD", minGrade: 65, minEnglish: 6.5, minEnglishBand: 6.0, intakes: ["feb","jul"], source: "https://study.uq.edu.au", lastVerified: VERIFIED, dataQuality: "derived", notes: null },
  { id: "uq-mds",       universityId: "uq", name: "Master of Data Science", level: "masters", field: "data-science", tuitionMin: 49000, tuitionMax: 54000, tuitionCurrency: "AUD", minGrade: 65, minEnglish: 6.5, minEnglishBand: 6.0, intakes: ["feb","jul"], source: "https://study.uq.edu.au", lastVerified: VERIFIED, dataQuality: "derived", notes: null },
  { id: "uq-mnurs",     universityId: "uq", name: "Master of Nursing (Graduate Entry)", level: "masters", field: "nursing", tuitionMin: 46000, tuitionMax: 50000, tuitionCurrency: "AUD", minGrade: 65, minEnglish: 7.0, minEnglishBand: 7.0, intakes: ["feb"], source: "https://study.uq.edu.au", lastVerified: VERIFIED, dataQuality: "derived", notes: "AHPRA registration required" },
  { id: "uq-mcom",      universityId: "uq", name: "Master of Commerce", level: "masters", field: "business", tuitionMin: 48000, tuitionMax: 53000, tuitionCurrency: "AUD", minGrade: 65, minEnglish: 6.5, minEnglishBand: 6.0, intakes: ["feb","jul"], source: "https://study.uq.edu.au", lastVerified: VERIFIED, dataQuality: "derived", notes: null },

  // UWA
  { id: "uwa-bcom",     universityId: "uwa", name: "Bachelor of Commerce", level: "bachelors", field: "business", tuitionMin: 42000, tuitionMax: 47000, tuitionCurrency: "AUD", minGrade: 75, minEnglish: 6.5, minEnglishBand: 6.0, intakes: ["feb","jul"], source: "https://www.uwa.edu.au", lastVerified: VERIFIED, dataQuality: "derived", notes: null },
  { id: "uwa-mit",      universityId: "uwa", name: "Master of Information Technology", level: "masters", field: "computer-science", tuitionMin: 41000, tuitionMax: 46000, tuitionCurrency: "AUD", minGrade: 50, minEnglish: 6.5, minEnglishBand: 6.0, intakes: ["feb","jul"], source: "https://www.uwa.edu.au", lastVerified: VERIFIED, dataQuality: "derived", notes: null },
  { id: "uwa-mpe",      universityId: "uwa", name: "Master of Professional Engineering", level: "masters", field: "engineering", tuitionMin: 47000, tuitionMax: 52000, tuitionCurrency: "AUD", minGrade: 65, minEnglish: 6.5, minEnglishBand: 6.0, intakes: ["feb","jul"], source: "https://www.uwa.edu.au", lastVerified: VERIFIED, dataQuality: "derived", notes: null },
  { id: "uwa-mnurs",    universityId: "uwa", name: "Master of Nursing Science", level: "masters", field: "nursing", tuitionMin: 42000, tuitionMax: 46000, tuitionCurrency: "AUD", minGrade: 65, minEnglish: 7.0, minEnglishBand: 7.0, intakes: ["feb"], source: "https://www.uwa.edu.au", lastVerified: VERIFIED, dataQuality: "derived", notes: "AHPRA registration required" },

  // Adelaide
  { id: "adelaide-beng", universityId: "adelaide", name: "Bachelor of Engineering", level: "bachelors", field: "engineering", tuitionMin: 47000, tuitionMax: 52000, tuitionCurrency: "AUD", minGrade: 75, minEnglish: 6.5, minEnglishBand: 6.0, intakes: ["feb","jul"], source: "https://www.adelaide.edu.au", lastVerified: VERIFIED, dataQuality: "derived", notes: null },
  { id: "adelaide-mcs",  universityId: "adelaide", name: "Master of Computer Science", level: "masters", field: "computer-science", tuitionMin: 45000, tuitionMax: 50000, tuitionCurrency: "AUD", minGrade: 65, minEnglish: 6.5, minEnglishBand: 6.0, intakes: ["feb","jul"], source: "https://www.adelaide.edu.au", lastVerified: VERIFIED, dataQuality: "derived", notes: null },
  { id: "adelaide-maf",  universityId: "adelaide", name: "Master of Accounting & Finance", level: "masters", field: "accounting", tuitionMin: 47000, tuitionMax: 52000, tuitionCurrency: "AUD", minGrade: 65, minEnglish: 6.5, minEnglishBand: 6.0, intakes: ["feb","jul"], source: "https://www.adelaide.edu.au", lastVerified: VERIFIED, dataQuality: "derived", notes: null },
  { id: "adelaide-mds",  universityId: "adelaide", name: "Master of Data Science", level: "masters", field: "data-science", tuitionMin: 47000, tuitionMax: 52000, tuitionCurrency: "AUD", minGrade: 65, minEnglish: 6.5, minEnglishBand: 6.0, intakes: ["feb","jul"], source: "https://www.adelaide.edu.au", lastVerified: VERIFIED, dataQuality: "derived", notes: null },

  // UTS
  { id: "uts-bit",      universityId: "uts", name: "Bachelor of IT", level: "bachelors", field: "computer-science", tuitionMin: 42000, tuitionMax: 47000, tuitionCurrency: "AUD", minGrade: 70, minEnglish: 6.5, minEnglishBand: 6.0, intakes: ["feb","jul"], source: "https://www.uts.edu.au", lastVerified: VERIFIED, dataQuality: "primary", notes: null },
  { id: "uts-mit",      universityId: "uts", name: "Master of IT", level: "masters", field: "computer-science", tuitionMin: 41000, tuitionMax: 46000, tuitionCurrency: "AUD", minGrade: 60, minEnglish: 6.5, minEnglishBand: 6.0, intakes: ["feb","jul"], source: "https://www.uts.edu.au", lastVerified: VERIFIED, dataQuality: "primary", notes: null },
  { id: "uts-meng",     universityId: "uts", name: "Master of Engineering", level: "masters", field: "engineering", tuitionMin: 42000, tuitionMax: 47000, tuitionCurrency: "AUD", minGrade: 60, minEnglish: 6.5, minEnglishBand: 6.0, intakes: ["feb","jul"], source: "https://www.uts.edu.au", lastVerified: VERIFIED, dataQuality: "primary", notes: null },
  { id: "uts-mba",      universityId: "uts", name: "Master of Business Analytics", level: "masters", field: "business", tuitionMin: 47000, tuitionMax: 52000, tuitionCurrency: "AUD", minGrade: 60, minEnglish: 6.5, minEnglishBand: 6.0, intakes: ["feb","jul"], source: "https://www.uts.edu.au", lastVerified: VERIFIED, dataQuality: "primary", notes: null },
  { id: "uts-mnurs",    universityId: "uts", name: "Master of Nursing (Graduate Entry)", level: "masters", field: "nursing", tuitionMin: 42000, tuitionMax: 46000, tuitionCurrency: "AUD", minGrade: 65, minEnglish: 7.0, minEnglishBand: 7.0, intakes: ["feb"], source: "https://www.uts.edu.au", lastVerified: VERIFIED, dataQuality: "primary", notes: "AHPRA registration required" },

  // RMIT
  { id: "rmit-bit",     universityId: "rmit", name: "Bachelor of IT", level: "bachelors", field: "computer-science", tuitionMin: 38400, tuitionMax: 38400, tuitionCurrency: "AUD", minGrade: 65, minEnglish: 6.5, minEnglishBand: 6.0, intakes: ["feb","jul"], source: "https://www.rmit.edu.au", lastVerified: VERIFIED, dataQuality: "primary", notes: null },
  { id: "rmit-mit",     universityId: "rmit", name: "Master of IT", level: "masters", field: "computer-science", tuitionMin: 38400, tuitionMax: 38400, tuitionCurrency: "AUD", minGrade: 65, minEnglish: 6.5, minEnglishBand: 6.0, intakes: ["feb","jul"], source: "https://www.rmit.edu.au", lastVerified: VERIFIED, dataQuality: "primary", notes: null },
  { id: "rmit-meng",    universityId: "rmit", name: "Master of Engineering", level: "masters", field: "engineering", tuitionMin: 38400, tuitionMax: 42000, tuitionCurrency: "AUD", minGrade: 65, minEnglish: 6.5, minEnglishBand: 6.0, intakes: ["feb","jul"], source: "https://www.rmit.edu.au", lastVerified: VERIFIED, dataQuality: "primary", notes: null },
  { id: "rmit-mds",     universityId: "rmit", name: "Master of Data Science", level: "masters", field: "data-science", tuitionMin: 38400, tuitionMax: 38400, tuitionCurrency: "AUD", minGrade: 65, minEnglish: 6.5, minEnglishBand: 6.0, intakes: ["feb","jul"], source: "https://www.rmit.edu.au", lastVerified: VERIFIED, dataQuality: "primary", notes: null },
  { id: "rmit-mnurs",   universityId: "rmit", name: "Master of Nursing", level: "masters", field: "nursing", tuitionMin: 39000, tuitionMax: 39000, tuitionCurrency: "AUD", minGrade: 65, minEnglish: 7.0, minEnglishBand: 7.0, intakes: ["feb","jul"], source: "https://www.rmit.edu.au", lastVerified: VERIFIED, dataQuality: "primary", notes: "AHPRA registration required" },

  // Macquarie
  { id: "macquarie-bit",  universityId: "macquarie", name: "Bachelor of IT", level: "bachelors", field: "computer-science", tuitionMin: 40000, tuitionMax: 44000, tuitionCurrency: "AUD", minGrade: 65, minEnglish: 6.5, minEnglishBand: 6.0, intakes: ["feb","jul"], source: "https://www.mq.edu.au", lastVerified: VERIFIED, dataQuality: "derived", notes: null },
  { id: "macquarie-mit",  universityId: "macquarie", name: "Master of IT", level: "masters", field: "computer-science", tuitionMin: 40000, tuitionMax: 44000, tuitionCurrency: "AUD", minGrade: 60, minEnglish: 6.5, minEnglishBand: 6.0, intakes: ["feb","jul"], source: "https://www.mq.edu.au", lastVerified: VERIFIED, dataQuality: "derived", notes: null },
  { id: "macquarie-macc", universityId: "macquarie", name: "Master of Accounting (CPA)", level: "masters", field: "accounting", tuitionMin: 44000, tuitionMax: 48000, tuitionCurrency: "AUD", minGrade: 60, minEnglish: 6.5, minEnglishBand: 6.0, intakes: ["feb","jul"], source: "https://www.mq.edu.au", lastVerified: VERIFIED, dataQuality: "derived", notes: null },
  { id: "macquarie-mds",  universityId: "macquarie", name: "Master of Data Science", level: "masters", field: "data-science", tuitionMin: 42000, tuitionMax: 46000, tuitionCurrency: "AUD", minGrade: 60, minEnglish: 6.5, minEnglishBand: 6.0, intakes: ["feb","jul"], source: "https://www.mq.edu.au", lastVerified: VERIFIED, dataQuality: "derived", notes: null },

  // Deakin
  { id: "deakin-bit",   universityId: "deakin", name: "Bachelor of IT", level: "bachelors", field: "computer-science", tuitionMin: 36000, tuitionMax: 40000, tuitionCurrency: "AUD", minGrade: 65, minEnglish: 6.0, minEnglishBand: 6.0, intakes: ["mar","jul","nov"], source: "https://www.deakin.edu.au", lastVerified: VERIFIED, dataQuality: "primary", notes: null },
  { id: "deakin-mit",   universityId: "deakin", name: "Master of IT", level: "masters", field: "computer-science", tuitionMin: 36000, tuitionMax: 40000, tuitionCurrency: "AUD", minGrade: 60, minEnglish: 6.5, minEnglishBand: 6.0, intakes: ["mar","jul","nov"], source: "https://www.deakin.edu.au", lastVerified: VERIFIED, dataQuality: "primary", notes: null },
  { id: "deakin-mba",   universityId: "deakin", name: "Master of Business Analytics", level: "masters", field: "business", tuitionMin: 40000, tuitionMax: 44000, tuitionCurrency: "AUD", minGrade: 60, minEnglish: 6.5, minEnglishBand: 6.0, intakes: ["mar","jul","nov"], source: "https://www.deakin.edu.au", lastVerified: VERIFIED, dataQuality: "primary", notes: null },
  { id: "deakin-mnurs", universityId: "deakin", name: "Master of Nursing Practice", level: "masters", field: "nursing", tuitionMin: 40000, tuitionMax: 44000, tuitionCurrency: "AUD", minGrade: 65, minEnglish: 7.0, minEnglishBand: 7.0, intakes: ["mar"], source: "https://www.deakin.edu.au", lastVerified: VERIFIED, dataQuality: "primary", notes: "AHPRA registration required" },

  // Curtin
  { id: "curtin-beng",  universityId: "curtin", name: "Bachelor of Engineering", level: "bachelors", field: "engineering", tuitionMin: 38000, tuitionMax: 42000, tuitionCurrency: "AUD", minGrade: 70, minEnglish: 6.5, minEnglishBand: 6.0, intakes: ["feb","jul"], source: "https://www.curtin.edu.au", lastVerified: VERIFIED, dataQuality: "derived", notes: null },
  { id: "curtin-mit",   universityId: "curtin", name: "Master of IT", level: "masters", field: "computer-science", tuitionMin: 30000, tuitionMax: 30000, tuitionCurrency: "AUD", minGrade: 60, minEnglish: 6.5, minEnglishBand: 6.0, intakes: ["feb","jul"], source: "https://www.curtin.edu.au", lastVerified: VERIFIED, dataQuality: "derived", notes: null },
  { id: "curtin-mcom",  universityId: "curtin", name: "Master of Commerce", level: "masters", field: "business", tuitionMin: 36000, tuitionMax: 40000, tuitionCurrency: "AUD", minGrade: 60, minEnglish: 6.5, minEnglishBand: 6.0, intakes: ["feb","jul"], source: "https://www.curtin.edu.au", lastVerified: VERIFIED, dataQuality: "derived", notes: null },
  { id: "curtin-mnurs", universityId: "curtin", name: "Master of Nursing Practice", level: "masters", field: "nursing", tuitionMin: 38000, tuitionMax: 42000, tuitionCurrency: "AUD", minGrade: 65, minEnglish: 7.0, minEnglishBand: 7.0, intakes: ["feb","jul"], source: "https://www.curtin.edu.au", lastVerified: VERIFIED, dataQuality: "derived", notes: "AHPRA registration required" },

  // La Trobe
  { id: "latrobe-bit",   universityId: "latrobe", name: "Bachelor of IT", level: "bachelors", field: "computer-science", tuitionMin: 36000, tuitionMax: 40000, tuitionCurrency: "AUD", minGrade: 60, minEnglish: 6.0, minEnglishBand: 6.0, intakes: ["mar","jul"], source: "https://www.latrobe.edu.au", lastVerified: VERIFIED, dataQuality: "derived", notes: null },
  { id: "latrobe-mit",   universityId: "latrobe", name: "Master of IT", level: "masters", field: "computer-science", tuitionMin: 36000, tuitionMax: 40000, tuitionCurrency: "AUD", minGrade: 60, minEnglish: 6.5, minEnglishBand: 6.0, intakes: ["mar","jul"], source: "https://www.latrobe.edu.au", lastVerified: VERIFIED, dataQuality: "derived", notes: null },
  { id: "latrobe-mba",   universityId: "latrobe", name: "Master of Business Analytics", level: "masters", field: "business", tuitionMin: 38000, tuitionMax: 42000, tuitionCurrency: "AUD", minGrade: 60, minEnglish: 6.5, minEnglishBand: 6.0, intakes: ["mar","jul"], source: "https://www.latrobe.edu.au", lastVerified: VERIFIED, dataQuality: "derived", notes: null },
  { id: "latrobe-mnurs", universityId: "latrobe", name: "Master of Nursing", level: "masters", field: "nursing", tuitionMin: 36000, tuitionMax: 40000, tuitionCurrency: "AUD", minGrade: 65, minEnglish: 7.0, minEnglishBand: 7.0, intakes: ["mar"], source: "https://www.latrobe.edu.au", lastVerified: VERIFIED, dataQuality: "derived", notes: "AHPRA registration required" },

  // Western Sydney University
  { id: "wsu-bit",      universityId: "wsu", name: "Bachelor of IT", level: "bachelors", field: "computer-science", tuitionMin: 34000, tuitionMax: 38000, tuitionCurrency: "AUD", minGrade: 60, minEnglish: 6.0, minEnglishBand: 6.0, intakes: ["mar","jul"], source: "https://www.westernsydney.edu.au", lastVerified: VERIFIED, dataQuality: "primary", notes: null },
  { id: "wsu-mit",      universityId: "wsu", name: "Master of IT", level: "masters", field: "computer-science", tuitionMin: 33000, tuitionMax: 37000, tuitionCurrency: "AUD", minGrade: 60, minEnglish: 6.5, minEnglishBand: 6.0, intakes: ["mar","jul"], source: "https://www.westernsydney.edu.au", lastVerified: VERIFIED, dataQuality: "primary", notes: null },
  { id: "wsu-mba",      universityId: "wsu", name: "Master of Business Administration", level: "masters", field: "business", tuitionMin: 36000, tuitionMax: 40000, tuitionCurrency: "AUD", minGrade: 60, minEnglish: 6.5, minEnglishBand: 6.0, intakes: ["mar","jul"], source: "https://www.westernsydney.edu.au", lastVerified: VERIFIED, dataQuality: "primary", notes: "Work experience required" },
  { id: "wsu-mnurs",    universityId: "wsu", name: "Master of Nursing (Graduate Entry)", level: "masters", field: "nursing", tuitionMin: 33000, tuitionMax: 37000, tuitionCurrency: "AUD", minGrade: 65, minEnglish: 7.0, minEnglishBand: 7.0, intakes: ["mar"], source: "https://www.westernsydney.edu.au", lastVerified: VERIFIED, dataQuality: "primary", notes: "AHPRA registration required" },
];
